TM1-6 Privacy Policy Url Browser Navigation
TechnoStudyMobile/Mova pull request #10
Opened 2023-06-15 19:05 UTC by svlilyas

:white_check_mark: Privacy Policy Url add
:white_check_mark: Extension for opening web page on device's browser add
:white_check_mark: Click listener add to Privacy Policy Linear Layout and navigates to Privacy Policy Url Page.

2023-06-17 09:29 UTC, Feyzarkt approved these changes
Good job 🙌

2023-06-19 02:39 UTC, oliver-basoglu commented on app/src/main/java/com/muratozturk/mova/common/Constants.kt
> +        const val PRIVACY_POLICY_URL = "https://github.com/TechnoStudyMobile/Mova#readme"
No need to put this into "object" class. "const val" can exist outside the class.

2023-06-19 02:39 UTC, oliver-basoglu commented on app/src/main/java/com/muratozturk/mova/ui/profile/ProfileFragment.kt
> +                 */
No need to add this comment since it's self-explanatory. It adds unnessary maintenance.

2023-06-19 02:42 UTC, oliver-basoglu requested changes

2023-06-19 02:42 UTC, oliver-basoglu commented on app/src/main/java/com/muratozturk/mova/common/Extensions.kt
> +        .also(::startActivity)
This is good looking code but a little misuse of Extension functions. Opening a webPage on browser would be better as a part of a different class such as "WebUtil". Which explains very well what's its doing. 
Opening another browser is not realated to Context, so using Extension function won't be a good choice.

2023-06-20 15:12 UTC, OkanDemirkol commented
Thanks!

2023-06-20 16:21 UTC, svlilyas commented
Bana atanan bir iş değildi. Çalışma amaçlı yaptım.

2023-06-20 16:21 UTC, closed without merging